[package]
name = "nes_ntsc-sys"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
name = "nes_ntsc_sys"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "1.1"
