[package]
name = "nes-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
nes-derive = { path = "../nes-derive" }
postcard = { version = "1.0.10", features = ["alloc"] }
