platform: x64
install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.exe"
    - rust-nightly-x86_64-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - set MING_BIN_DIR=C:\msys64\mingw64\bin
    - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin;%MING_BIN_DIR%;C:\msys64\usr\bin
    - rustc -V
    - cargo -V
build_script:
    - cargo build --verbose
test_script:
    - cargo test --release --no-fail-fast --verbose -p nes
after_build:
    - SET RELEASE_ARCHIVE=mass-nes-win-%APPVEYOR_REPO_TAG_NAME%.zip
    - IF %APPVEYOR_REPO_TAG% EQU true cargo build --release
    - IF %APPVEYOR_REPO_TAG% EQU true dir target\release
    - IF %APPVEYOR_REPO_TAG% EQU true 7z a %RELEASE_ARCHIVE% %APPVEYOR_BUILD_FOLDER%\target\release\mass_nes.exe
artifacts:
    - path: mass-nes-win-*.zip
      name: release
deploy:
    release: $(appveyor_repo_tag_name)
    description: "Release $(appveyor_repo_tag_name)"
    provider: GitHub
    auth_token:
        secure: RT2z44BsBy0A/5TLqTBV9bUKamA8My702nhJOGpHy7zup9nOSCCWzI1+PZzr2Wqh
    artifact: release
    force_update: true
    on:
        APPVEYOR_REPO_TAG: true


