language: rust
rust:
    - nightly
addons:
    apt:
        packages:
            - libasound2-dev
os:
    - linux
    - osx
sudo: required
dist: trusty
script:
    - cargo build --verbose
after_script:
    - cargo test --verbose --release --no-fail-fast -p nes
before_deploy:
    - cargo build --release
    - cd target/release
    - tar -zcvf mass-nes-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz mass_nes
    - cd ../..
deploy:
    provider: releases
    api_key:
        secure: OZR4S2qmHnuoSqT7v9UiMKsvS0B5N4bs+EnfaoqEHqqJ+DCTKYtOjo0lpQxakIfuY5PDrUCMNvOc9NchZWKxeCQTE4dRBST8jgCY3IjATCpGRDj8ZxwSWBDqs/Q1QNt9nah5xoMu/mmb3nera8Jf/Ia5QeO0imeQ2F0UIO7jgWNWR8GTTebFM69Pd4mC4+GpGycE/j+LPGD1Tf3b3/tcPD8F856zGQI4gKZUD68I8dj9Q4w0MqVVq477TNc8SSKdDAZkA68I2RwGAqnKJfAYNNNpWiTOZ/fXJU7HSwxIfCvb7UPP+Mu3AIrAomtlPuoa7GNZb68udPEhVyXuyIa45YJ42UyfA216bUwmbeY3zMDWtPE3kqDSXBoXrQ1VWI7ZQIpP2IrlIx3CQ8jfhHxVvE6iC2gktIWwR6G5VtC2DqHH4WexTsZ9zh4uWNCAWuVCF+kFAwGC5T8SgZKplpHbmszqTEz+slj/e8fARaDV96tait6bNiXxoRmeDywUOn4DRJJyTr4zdFKK5wc612jaR0uhdiHMfJ+bZ1eMtjO4XADPD+m4jb8kQ+al6vwkISXazhVdY3PUP59oHEjFUcDpdiUEQWMd3PobFf+ms6IwGYZHyypa0CId2vp4+ikzpqmCVr/RuJOd7Bx+qavym+aU2XfthXXY1I5fHae3WSOlYEI=
    file: target/release/mass-nes-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
    overwrite: true
    skip_cleanup: true
    on:
        tags: true
notifications:
    email: false
