[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.4"
authors = ["Nick Massey <nickmass@nickmass.com>"]
license = "MIT"
edition = "2024"

[profile.dev]
opt-level = 1
