[package]
name = "mass_nes"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]

[dependencies]
glium = "0.15"
cpal = "0.4"
futures = "0.1.1"
blip_buf = "0.1"
rodio = "0.4"
clap = "2"
nes_ntsc = { path = "nes_ntsc", version = "0.1"}
