[package]
name = "mass_nes"
version = "0.1.0"
edition = "2018"
authors = ["Nick Massey <nickmass@nickmass.com>"]

[dependencies]
blip_buf = "0.1"
clap = "2.33"
cpal = "0.12"
crossbeam = "0.7"
glium = "0.27"
nes = { path = "nes" }
nes_ntsc = { path = "nes_ntsc", version = "0.1"}
