[package]
name = "nes-ntsc-rust"
version = "0.1.0"
edition = "2021"
authors = ["Nick Massey <nickmass@nickmass.com>", "Shay Green"]
license = "LGPL-2.1-or-later"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
nes_ntsc-sys = { path = "../nes_ntsc-sys" }
