[package]
name = "nes-ntsc-rust"
version.workspace = true
edition.workspace = true
authors = ["Nick Massey <nickmass@nickmass.com>", "Shay Green"]
license = "LGPL-2.1-or-later"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
nes_ntsc-sys = { path = "../nes_ntsc-sys" }
