[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
nes = { path = "../nes" }
gilrs = "0.10.9"
winit = "0.30.5"
bytemuck = "1.18.0"
const_format = "0.2.33"
log = "0.4.22"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nes_ntsc = { path = "../nes_ntsc", version = "0.1"}
cpal = { version = "0.15" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
nes_ntsc-c2rust = { path = "../nes_ntsc-c2rust", version = "0.1"}
cpal = { version = "0.15",  features = ["wasm-bindgen"] }
