[package]
name = "nes_ntsc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
nes_ntsc-sys = { path = "../nes_ntsc-sys", version = "0.1" }
