[package]
name = "mass_nes"
version = "0.1.0"
edition = "2021"
authors = ["Nick Massey <nickmass@nickmass.com>"]

[dependencies]
blip_buf = "0.1"
clap = { version = "4.5", features = ["derive"] }
crossbeam = "0.8"
nes = { path = "../nes" }
glium = { git = "https://github.com/nickmass/glium.git", features = ["simple_window_builder"] }
ui = { path = "../ui" }
log = "0.4.22"
