[package]
name = "nes_ntsc-sys"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]
build = "build.rs"

[lib]
name = "nes_ntsc_sys"
path = "lib.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
