[package]
authors = ["Nick Massey <nickmass@nickmass.com>"]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4"

[dependencies.nes]
path = "../nes"
